// Import generated component images
import ramImage from '@assets/generated_images/DDR5_RAM_memory_modules_fd65b551.png';
import motherboardImage from '@assets/generated_images/Gaming_motherboard_PCB_4a9b228d.png';
import caseImage from '@assets/generated_images/Mini-ITX_PC_case_884e7917.png';
import cpuImage from '@assets/generated_images/Modern_CPU_processor_63e5b0b8.png';
import gpuImage from '@assets/generated_images/Modern_GPU_graphics_card_bb85da54.png';
import { PCComponent, BuildPreset } from '@shared/schema';

import { ComponentWithDescriptions } from './beginnerMode';

//todo: remove mock functionality - this is temporary mock data for the prototype
export const mockComponents: ComponentWithDescriptions[] = [
  {
    id: '1',
    name: 'RTX 4080 SUPER FE',
    brand: 'NVIDIA',
    category: 'GPU',
    price: 999,
    spec: '16GB GDDR6X',
    simpleDescription: 'Powerful graphics card for 4K gaming and content creation',
    technicalDescription: '16GB GDDR6X memory, 320-bit bus, 2230 MHz base clock, PCIe 4.0 x16',
    imageUrl: gpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '2',
    name: 'Ryzen 7 7800X3D',
    brand: 'AMD',
    category: 'CPU',
    price: 389,
    spec: '8c/16t, 5.0GHz',
    simpleDescription: 'Fast processor perfect for gaming and multitasking',
    technicalDescription:
      '8 cores/16 threads, 4.2GHz base, 5.0GHz boost, AM5 socket, 96MB L3 cache',
    imageUrl: cpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '3',
    name: 'Ripjaws S5 64GB',
    brand: 'G.Skill',
    category: 'RAM',
    price: 179,
    spec: 'DDR5-6000',
    simpleDescription: 'Fast memory for smooth performance and quick loading',
    technicalDescription: '64GB (2x32GB) DDR5-6000 CL30-40-40-96, 1.35V, XMP 3.0 ready',
    imageUrl: ramImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '4',
    name: 'ROG Strix B650E-I',
    brand: 'ASUS',
    category: 'Motherboard',
    price: 329,
    spec: 'Mini-ITX, AM5',
    simpleDescription: 'Compact main board that connects all your components',
    technicalDescription:
      'Mini-ITX form factor, AM5 socket, B650E chipset, 12+2 VRM phases, PCIe 5.0',
    imageUrl: motherboardImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '5',
    name: 'Samsung 990 Pro 2TB',
    brand: 'Samsung',
    category: 'SSD',
    price: 169,
    spec: 'NVMe, 7000MB/s',
    simpleDescription: 'Super fast storage for quick boot times and file loading',
    technicalDescription:
      '2TB M.2 2280 NVMe SSD, PCIe 4.0 x4, 7000/6900 MB/s read/write, 3D V-NAND',
    imageUrl: '',
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '6',
    name: 'Fractal Terra',
    brand: 'Fractal Design',
    category: 'Case',
    price: 179,
    spec: 'Mini-ITX, SFF',
    simpleDescription: 'Compact case that fits everything while looking great on your desk',
    technicalDescription:
      'Mini-ITX chassis, 10.5L volume, supports GPUs up to 315mm, PSU up to 180mm',
    imageUrl: caseImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '7',
    name: 'Corsair SF750',
    brand: 'Corsair',
    category: 'PSU',
    price: 179,
    spec: '750W, SFX, 80+ Gold',
    simpleDescription: 'Reliable power supply that efficiently powers your entire system',
    technicalDescription:
      '750W SFX form factor, 80+ Gold efficiency, fully modular, 40mm fan, 125mm length',
    imageUrl: '',
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '8',
    name: 'Noctua NH-L12S',
    brand: 'Noctua',
    category: 'Cooler',
    price: 69,
    spec: 'Low-profile, 70W TDP',
    simpleDescription: 'Quiet cooler that keeps your processor at safe temperatures',
    technicalDescription:
      'Low-profile CPU cooler, 70W TDP, dual-fan design, 70mm height, AM5 compatible',
    imageUrl: '',
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '9',
    name: 'RTX 4060',
    brand: 'NVIDIA',
    category: 'GPU',
    price: 299,
    spec: '8GB GDDR6',
    simpleDescription: 'Great graphics card for 1080p gaming with excellent efficiency',
    technicalDescription: '8GB GDDR6 memory, 128-bit bus, 2460 MHz base clock, PCIe 4.0 x8, DLSS 3',
    imageUrl: gpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '10',
    name: 'RX 7600 XT',
    brand: 'AMD',
    category: 'GPU',
    price: 329,
    spec: '16GB GDDR6',
    simpleDescription: 'Powerful graphics card perfect for 1440p gaming',
    technicalDescription:
      '16GB GDDR6 memory, 128-bit bus, 2755 MHz boost clock, PCIe 4.0 x16, FSR 3',
    imageUrl: gpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '11',
    name: 'Ryzen 5 7600',
    brand: 'AMD',
    category: 'CPU',
    price: 229,
    spec: '6c/12t, 5.1GHz',
    simpleDescription: 'Fast processor perfect for gaming with great value',
    technicalDescription:
      '6 cores/12 threads, 3.8GHz base, 5.1GHz boost, AM5 socket, 32MB L3 cache',
    imageUrl: cpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '12',
    name: 'MSI B650M Pro',
    brand: 'MSI',
    category: 'Motherboard',
    price: 149,
    spec: 'Micro-ATX, AM5',
    simpleDescription: 'Reliable main board with all essential features',
    technicalDescription:
      'Micro-ATX form factor, AM5 socket, B650 chipset, 10+2+1 VRM phases, PCIe 4.0',
    imageUrl: motherboardImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '13',
    name: 'Corsair Vengeance 32GB',
    brand: 'Corsair',
    category: 'RAM',
    price: 129,
    spec: 'DDR5-5600',
    simpleDescription: 'Fast memory for smooth gaming and multitasking',
    technicalDescription: '32GB (2x16GB) DDR5-5600 CL36-36-36-76, 1.25V, XMP 3.0 ready',
    imageUrl: ramImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '14',
    name: 'Corsair 4000D',
    brand: 'Corsair',
    category: 'Case',
    price: 99,
    spec: 'Mid-Tower, ATX',
    simpleDescription: 'Spacious case with excellent airflow and cable management',
    technicalDescription:
      'Mid-tower ATX chassis, supports GPUs up to 360mm, PSU up to 180mm, excellent cable management',
    imageUrl: caseImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '15',
    name: 'EVGA 650W GQ',
    brand: 'EVGA',
    category: 'PSU',
    price: 89,
    spec: '650W, ATX, 80+ Gold',
    simpleDescription: 'Reliable power supply with enough capacity for most builds',
    technicalDescription:
      '650W ATX form factor, 80+ Gold efficiency, semi-modular, 140mm fan, 160mm length',
    imageUrl: '',
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '16',
    name: 'RX 6650 XT',
    brand: 'AMD',
    category: 'GPU',
    price: 249,
    spec: '8GB GDDR6',
    simpleDescription: 'Excellent graphics card for 1080p high and 1440p medium gaming',
    technicalDescription:
      '8GB GDDR6 memory, 128-bit bus, 2635 MHz boost clock, PCIe 4.0 x16, FSR 2',
    imageUrl: gpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '17',
    name: 'Corsair Vengeance 16GB',
    brand: 'Corsair',
    category: 'RAM',
    price: 79,
    spec: 'DDR5-5600',
    simpleDescription: 'Fast memory for smooth gaming performance',
    technicalDescription: '16GB (2x8GB) DDR5-5600 CL36-36-36-76, 1.25V, XMP 3.0 ready',
    imageUrl: ramImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '18',
    name: 'WD Blue SN580 1TB',
    brand: 'Western Digital',
    category: 'SSD',
    price: 89,
    spec: 'NVMe, 4150MB/s',
    simpleDescription: 'Fast storage for quick boot times and game loading',
    technicalDescription: '1TB M.2 2280 NVMe SSD, PCIe 4.0 x4, 4150/4150 MB/s read/write, 3D NAND',
    imageUrl: '',
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '19',
    name: 'ASRock A620M PRO RS',
    brand: 'ASRock',
    category: 'Motherboard',
    price: 89,
    spec: 'Micro-ATX, AM5',
    simpleDescription: 'Budget-friendly main board with essential features',
    technicalDescription:
      'Micro-ATX form factor, AM5 socket, A620 chipset, 8+2+1 VRM phases, PCIe 4.0 x16',
    imageUrl: motherboardImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '20',
    name: 'RX 6600',
    brand: 'AMD',
    category: 'GPU',
    price: 199,
    spec: '8GB GDDR6',
    simpleDescription: 'Great graphics card for 1080p high gaming',
    technicalDescription: '8GB GDDR6 memory, 128-bit bus, 2589 MHz boost clock, PCIe 4.0 x8, FSR 2',
    imageUrl: gpuImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '21',
    name: 'Thermaltake Versa H18',
    brand: 'Thermaltake',
    category: 'Case',
    price: 49,
    spec: 'Micro-ATX',
    simpleDescription: 'Affordable case with good airflow and build quality',
    technicalDescription:
      'Micro-ATX chassis, supports GPUs up to 350mm, PSU up to 180mm, pre-installed fan',
    imageUrl: caseImage,
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
  {
    id: '22',
    name: 'EVGA BR 500W',
    brand: 'EVGA',
    category: 'PSU',
    price: 59,
    spec: '500W, ATX, 80+ Bronze',
    simpleDescription: 'Budget power supply with enough capacity for gaming builds',
    technicalDescription: '500W ATX form factor, 80+ Bronze efficiency, 120mm fan, 140mm length',
    imageUrl: '',
    isAvailable: true,
    specUrl: null,
    verifiedAt: null,
    sourceNote: null,
    lastStatus: null,
    lastEtag: null,
    lastHash: null,
  },
];

//todo: remove mock functionality - this is temporary mock data for the prototype
export const mockPresets: BuildPreset[] = [
  {
    id: 'preset-1',
    name: 'Terra Stealth',
    tier: 'High-end SFF',
    price: 2999,
    description: 'Compact powerhouse for 4K gaming and content creation',
    components: JSON.stringify(['1', '2', '3', '4', '5', '6', '7', '8']),
  },
  {
    id: 'preset-2',
    name: 'Balanced 1440p',
    tier: 'Mid-range',
    price: 1699,
    description: 'Perfect for 1440p gaming with great price-to-performance ratio',
    components: JSON.stringify(['2', '3', '4', '5', '6', '7', '8']),
  },
  {
    id: 'preset-3',
    name: 'Starter Esports',
    tier: 'Entry',
    price: 899,
    description: 'Competitive gaming build for high frame rates at 1080p',
    components: JSON.stringify(['2', '4', '5', '6', '7', '8']),
  },
  // Console Killer Presets
  {
    id: 'console-ps5',
    name: 'PS5 Equivalent',
    tier: 'Entry',
    price: 793,
    description: 'Matches PS5 performance at 1080p high settings, uses stock cooler',
    components: JSON.stringify(['20', '11', '19', '17', '18', '21', '22']),
  },
  {
    id: 'console-xbox',
    name: 'Xbox Series X Equivalent',
    tier: 'Entry',
    price: 843,
    description:
      'Approaches Series X at 1440p medium/high in many titles; expect variation by game and settings',
    components: JSON.stringify(['16', '11', '19', '17', '18', '21', '22']),
  },
];
